name: Node.js CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_call:

jobs:
  test:
    name: Test

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node-version:
          - current
          - lts/*
          - lts/-1

    steps:
      - uses: actions/checkout@v3
      - name: Install MeCab
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends mecab
          mecab --version
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test

  lint:
    name: Lint

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js LTS
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: npm
      - run: npm ci
      - run: npm run lint --if-present
